### ISSUE TITLE
Task was destroyed but is pending!

### ISSUE THREAD

**Issue by al-little** [webfucktory/python-events-manager#5]
I ran into an issue when running multiple tasks inside an asyncio loop.

Issue: https://docs.python.org/3/library/asyncio-task.html#asyncio.create_task

**When creating a task you must hang on to a reference in case it gets garbage collected.**

Fix: I created a fix strongly influenced by the asyncio manual :D

__init__.py
Add a new set to hold references:
_listeners: ListenersType = {}
_background_tasks = set()

Modify emit to hold the references (and discard on completion)
def emit(e: Event) -> None:
    task = create_task(__run_listeners(e))
    _background_tasks.add(task)
    task.add_done_callback(_background_tasks.discard)

Modify __run_listeners to also hold a reference
async def __run_listeners(e: Event) -> None:
    listeners = _listeners.get(e.__class__) or []

    for (listener, (args, kwargs)) in listeners:
        task = create_task(__run_listener(e, listener, *args, **kwargs))
        _background_tasks.add(task)
        task.add_done_callback(_background_tasks.discard)

I have tested the fix with some fairly complex code and it's happy.

Hope this helps, and thanks very much for the package!

**Comment by albertogferrario** [comment]
https://github.com/webfucktory/python-events-manager/pull/6

**Comment by albertogferrario** [comment]
solved in [`v0.2.2`](https://github.com/webfucktory/python-events-manager/releases/tag/v0.2.2)
